from enum import Enum


class PaymentAuthenticationType(str, Enum):
    THREE_DS = "THREE_DS"
    NON_THREE_DS = "NON_THREE_DS"
    BKM_EXPRESS = "BKM_EXPRESS"
    THREE_DS_FALLBACK_TO_NON_THREE_DS = "THREE_DS_FALLBACK_TO_NON_THREE_DS"
    GOOGLEPAY = "GOOGLEPAY"
    APPLEPAY = "APPLEPAY"
    YKB_WORLD_PAY = "YKB_WORLD_PAY"
    YKB_WORLD_PAY_SHOPPING_LOAN = "YKB_WORLD_PAY_SHOPPING_LOAN"
    GARANTI_PAY = "GARANTI_PAY"
    JUZDAN = "JUZDAN"
